### PR TITLE
add spec augment

### PR DESCRIPTION
**Pull request by cookingbear**

### CODE REVIEW

**Review by tjadamlee — COMMENTED** [review]
please give some experimental results on aishell and hkust, then we can merge into the master

**Review by chenguoguo — COMMENTED** [review]
Generally looks good to me. A suggestion maybe for future reference: spec augmentation is only one type of pre-processing that we do, we can do noise augmentation, reverberation augmentation, etc. as well. So it will be better if we have a more general AudioPreProcessing class here. @tjadamlee your call if we do it now or later.

**Comment by cookingbear** [comment]
> please give some experimental results on aishell and hkust, then we can merge into the master

ok I would show experimental results after validation.

**Comment by tjadamlee** [comment]
> Generally looks good to me. A suggestion maybe for future reference: spec augmentation is only one type of pre-processing that we do, we can do noise augmentation, reverberation augmentation, etc. as well. So it will be better if we have a more general AudioPreProcessing class here. @tjadamlee your call if we do it now or later.

I

**Comment by tjadamlee** [comment]
@chenguoguo I think, a better way is to implement all these in the transform component. I will check this

**Pull request closed without merging**
