### PR TITLE
decode branch merge

### PR DESCRIPTION
**Pull request by cookingbear**
In this update, 
1. move the decoding initialization part out of the model to prevent repeated initialization
2. rewrite the parallelizable part in TensorFlow in ctc_scorer
3. add wfst adaption
4. update related docs
4. this update has been tested that It does not change the decoding accuracy in the beam search mode but improve decoding speed more than 2 times.

### CODE REVIEW

**Review by Some-random — COMMENTED** [review]
I've tested @cookingbear 's new implementation for decoder and got the same decoding results with much less decoding time.

But this pull request obviously affects a lot of files and concerns the implementation of decoding interface. Could you help reviewing this pull request when you're free @tjadamlee @godjealous ?

**Comment by iou2much** [comment]
@cookingbear @Some-random 
Thanks for your work. I also wanna try it out . Could you help to provide the JSON config, as an example?

**Comment by iou2much** [comment]
Would be better to have a tutorial for instructing how to use this feature and how to make the WFST graph ? Thank you:)

**Comment by cookingbear** [comment]
wfst adaption and decoding speed acceleration will be updated in new pull requests respectively

**Pull request closed without merging**
