### PR TITLE
supports loading kaldi-format data

### PR DESCRIPTION
**Pull request by neneluo**
1. Speed: Sorting and filtering data are slow due to traversing all data, and they can be turned off in codes. The speed during training is similar to loading csv-format data.
2. Correctness: (1) receives similar accuracies in the same epoch.  (2) calculated cmvn is very close to the cmvn calculated by csv-format data. (The difference might be because of the difference in the effective numbers of feats.)

### CODE REVIEW

**Comment by tjadamlee** [comment]
suggest: add a new python file as athena/data/datasets/speech_recognition_kaldiio.py seperately

**Comment by neneluo** [comment]
> suggest: add a new python file as athena/data/datasets/speech_recognition_kaldiio.py seperately

Sure. I'll update it.

**Comment by shuaijiang** [comment]
> > suggest: add a new python file as athena/data/datasets/speech_recognition_kaldiio.py seperately
> 
> Sure. I'll update it.

Better reuse the filters codes in  athena/data/datasets/speech_recognition.py

**Comment by Some-random** [comment]
close this pr for now, please push again

**Review by tjadamlee — APPROVED** [review]

**Review by tjadamlee — APPROVED** [review]

**Pull request merged**
